[project]
name = "cosmererpgencountercalculator"
version = "0.1.0"
description = "A simple calculator to help quickly build Combat Scenes in the Cosmere RPG by Brotherwise Games."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
